export enum StoryGenre {
  FANTASY = 'Fantasy',
  SCI_FI = 'Sci-Fi',
  MYSTERY = 'Mystery',
  HORROR = 'Horror',
  ROMANCE = 'Romance',
  ADVENTURE = 'Adventure',
  CHILDREN = 'Children'
}

export enum ArtStyle {
  REALISTIC = 'Realistic',
  ANIME = 'Anime',
  WATERCOLOR = 'Watercolor',
  CYBERPUNK = 'Cyberpunk',
  PIXEL_ART = 'Pixel Art',
  OIL_PAINTING = 'Oil Painting',
  THREE_D_RENDER = '3D Render'
}

export interface StoryParams {
  prompt: string;
  genre: StoryGenre;
  artStyle: ArtStyle;
}

export interface GeneratedStory {
  id: string;
  title: string;
  content: string;
  imagePrompt: string; // Generated by AI to guide the image model
  imageUrl?: string;
  audioUrl?: string; // We will use a blob URL for the audio
  audioBase64?: string; // Store base64 to regenerate blob if needed
  timestamp: number;
  params: StoryParams;
}

export interface LoadingState {
  status: 'idle' | 'generating_text' | 'generating_image' | 'generating_audio' | 'complete' | 'error';
  message?: string;
}
